### ISSUE TITLE
Return real path for files accessible from sandbox

### ISSUE THREAD

**Issue by grulja** [flatpak/xdg-desktop-portal#141]
When opening a file using FileChooser portal, you get the file exported through Document portal and the path is something like "/run/user/1001/doc/xxxxxx/foo". While this is not problem most of the time, it becomes a problem when you want to import a project into some IDE (e.g. Qt Creator). To support this, we need to actually allow the application access to $HOME to be able import projects but problem is that FileChooser portal gets always involved. What would solve this issue is returning real path of the file in case the application has direct access to it.

KDE bugreport: https://bugs.kde.org/show_bug.cgi?id=388090

**Comment by amtlib-dot-dll** [comment]
1. When $HOME is accessible, there is no need for the Document Portal
2. If so, this would be a huge security hole, obviously
3. The Document Portal should be redesigned, in my opinion. Usually we only need to open files inside `$HOME`, and one solution is to provide `/home` inside the sandbox as a `tmpfs` and bind mount certain files or directories after the user grants it, eliminating the need for `/run/user/$(id -u)/doc`. Another challenging solution is to provide `/home` as `fuse` 😂

**Comment by phw** [comment]
Probably related: https://github.com/flatpak/xdg-desktop-portal/issues/95

**Comment by matthiasclasen** [comment]
I think this was fixed by the merge

**Comment by grulja** [comment]
It's not fixed completely, still missing to return real path when saving files, see https://github.com/flatpak/xdg-desktop-portal/pull/148.

**Comment by Alexander-Wilms** [comment]
The use case "opening a file" doesn't seem to be covered by the merged PR, right? I want to open a .tex file with xdg-desktop-portal-kde, and need the real path so that lualatex can read included files and write temporary files and the pdf to the same directory, cf. https://github.com/flathub/flathub/pull/381

Running `rm /run/run/user/1000/flatpak-info` fixes this issue, cf. https://github.com/flatpak/flatpak/issues/1276

**Comment by grulja** [comment]
There was a bug recently in flatpak breaking this feature, it should be fixed in the latest version.

**Comment by Alexander-Wilms** [comment]
Do you mean this issue: https://github.com/flatpak/flatpak/issues/1307#issuecomment-384684499 ?

I'm running Fedora 28, which has Flatpak 0.11.7 so maybe that's a different issue?

**Comment by grulja** [comment]
I just tested it with org.kde.kate (both open and save) and it returned correct url in both cases so the issue should be fixed. Tested on Fedora 28 with flatpak-0.11.7.1 and xdg-desktop-portal-0.11-1.

**Comment by Alexander-Wilms** [comment]
Right, I wonder what makes the difference.

**Comment by Alexander-Wilms** [comment]
I still encounter this issue with Keepass and TeXstudio on Fedora 29 with flatpak 1.2.3, xdg-desktop-portal 1.2.0 and xdg-desktop-portal-kde 5.14.5.

Should I open a new issue?

**Comment by AsavarTzeth** [comment]
Correct me if I'm wrong but currently the host (real) path is only returned if the app has direct filesystem access? i.e. not sandboxed in that respect.

KeePassXC does not have direct filesystem permissions. It is sandboxed and makes full use of the filechooser and document portals. Returning the real path instead would just cause an error.

Or are we expecting the filechooser portal to return both the host and the document portal path? The first for actual use, and the second for display to the user. How would that even work without (flatpak specific) changes to Qt, apps, etc?

**Comment by Alexander-Wilms** [comment]
Even if I use --filesystem=host, KeepassXC and TeXstudio show a /run/user... path

**Comment by grulja** [comment]
I tried now with org.flatpak.qtdemo and the path is **$HOME/user/path/to/file**, which is expected. With KeepassXC I get same result as you mentioned, but my guess it's because I'm opening a file which I previously opened through the document portal and thus I get **/run/user/1000/doc/file** path.

**Comment by Alexander-Wilms** [comment]
I repeated my test with new files, with filenames I've never used before and I still get /run/user... paths...
