### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by war1025** [flatpak/xdg-desktop-portal#1416]
### Operating System

Debian

### XDG Desktop Portal version

1.18

### Desktop Environment

GNOME

### Expected Behavior

I would expect this to use a very minimal amount of ram.

### Current Behavior

This is consistently the most memory intensive process on my machine.
Killing it does absolutely nothing bad as far as I can tell, so whatever it is up to can't be that critical for it to be using so much ram, and when it restarts it is back to minimal memory usage.
This is why I assume it's just leaking like a sieve somewhere.

![Screenshot from 2024-08-10 01-36-11](https://github.com/user-attachments/assets/58fa05f0-1148-4a9b-94dc-af3c7ab42a5c)

### Steps to Reproduce

Use my computer for a day.

**Comment by GeorgesStavracas** [comment]
Lots of memory leaks were fixed in the `main` branch, can you please test it?

**Comment by hfiguiere** [comment]
is this `xdg-desktop-portal` or any of the implementations like `xdg-desktop-portal-gtk` or `xdg-desktop-portal-gnome`

`xdg-desktop-portal-gnome` has some known issues, but it's not this project.

**Comment by A6GibKm** [comment]
Does this issue persist? You can use

    ps aux |grep xdg-desktop-por
    
 To see to which `xdg-desktop-por`... the PID comes from.

**Comment by swick** [comment]
We support asan builds `-Db_sanitize=address -Db_lundef=false`. You can try running such a build and capture the output.

**Comment by aliaksandr-trush** [comment]
Hi @swick ,
I've tried to run with asan build, but didn't receive any useful information: https://gist.github.com/aliaksandr-trush/03001b3c8095011cc471253635c751f2 (I am not sure that I've run build correctly. Let me know if I need to do it in another way).
And xdg-desktop-portal process was killed by OOM Killer (process consumer > 12 Gb or memory)

**Comment by hfiguiere** [comment]
You only get the asan leaks report when xdg-desktop-portal terminates. `kill -HUP` on the xdg-desktop-portal process should trigger it.

**Comment by swick** [comment]
You can introduce a problem on purpose (e.g. in main `char *xxx = (char*)malloc(10 * sizeof(char*));`) and see if you get the asan output.

If that's the case, then maybe `cat /proc/$PID/maps` or `ls -la /proc/$PID/fd/` might help, because it does sound like some other resource is getting lost.

**Comment by swick** [comment]
Nothing suspicious in there. Let's go with valgrind next! `valgrind --leak-check=yes /usr/libexec/xdg-desktop-portal --replace`

**Comment by swick** [comment]
Please refrain from adding comments which add no new information.

**Comment by aliaksandr-trush** [comment]
@swick I've added the latest logs into previous comment. Please take a look and let me know if I can provide any additional information that could be helpful.

**Comment by DavidNorena** [comment]
I dont know if it adds info on how to replicate, Im on arch linux, and nvtop shows this

```
PID USER DEV     TYPE  GPU        GPU MEM    CPU  HOST MEM Command
76958 user   0 Both G+C   0%    147MiB   4%     0%    267MiB /usr/lib/xdg-desktop-portal-kde
```

Is there a way to just configure which gpu to use ? DRI_PRIME=1 maybe ?

On the other hand, the best way to replicate is, screen sharing in teams, or google ai studio has a screen share as well, and after some minutes my CPU gets hot as hell and unresponsive system

**Comment by aliaksandr-trush** [comment]
@swick 
Attaching bt full for issue related to hash: [hashlogs.txt](https://github.com/user-attachments/files/21890929/hashlogs.txt)

I'll try to read information about sysprof and pcap file and how to use them and attach information.

**Comment by aliaksandr-trush** [comment]
@swick not really.
The issue usually could be reproduced after ~3d process uptime. Sysprof and tcpdump in my case unable to handle such long run and crash the system.

**Comment by aliaksandr-trush** [comment]
Hello @swick,

This is the link to Sysprof file generated today: https://drive.proton.me/urls/BPF8TPEG2G#iMYxvLArjc85

p.s.
I've realized, that I have the issue when f-person/auto-dark-mode.nvim Neovim plugin enabled. The plugin is running the following command under the hood: `dbus-send--session --print-reply=literal --reply-timeout=1000 --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:org.freedesktop.appearance string:color-scheme`.
After closing all Neovim instances, CPU usage back to normal, but Memory usage remains the same.

**Comment by aliaksandr-trush** [comment]
I do not see huge memory usage from `xdg-desktop-portal-gnome` or `xdg-desktop-portal-gtk` :

<img width="871" height="192" alt="Image" src="https://github.com/user-attachments/assets/aef5cef4-b920-4a1a-9c26-22e53cf9cb49" />


This is 2 most active threads I see in Sysprof:

<img width="1412" height="871" alt="Image" src="https://github.com/user-attachments/assets/73479f28-250d-4293-aa03-7a0775e53dae" />

<img width="1412" height="871" alt="Image" src="https://github.com/user-attachments/assets/bfef64d0-1181-4af1-9ffe-53df53536187" />

**Comment by swick** [comment]
I ran `while true; do sleep 3; dbus-send --session --print-reply=literal --reply-timeout=1000 --dest=org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read string:org.freedesktop.appearance string:color-scheme; done` and nothing. Does the thing maybe have a bug where it just spams the call as fast as possible? If I do that, I can see the memory rising slowly and then not go down.

**Comment by aliaksandr-trush** [comment]
Default timeout between calls in the plugin is 1s. Also, several instances could be runned at the same time.

**Comment by dominikh** [comment]
All I can offer at this point is this evidence that xdg-desktop-portal 1.20.4 still holds on to a lot of memory:

```
> ps aux | grep xdg-desktop-portal
dominikh    5151  0.0  6.4 5365912 4214676 ?     Ssl  Apr27   0:56 /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-desktop-portal
dominikh    5158  0.0  0.0 309852  3904 ?        Ssl  Apr27   0:01 /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-permission-store
dominikh    5163  0.0  0.0 613504  4252 ?        Ssl  Apr27   0:04 /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-document-portal
dominikh    5734  0.0  0.0 496600 14964 ?        Ssl  Apr27   0:03 /nix/store/86zmqzjz652wlnaiv5v7byyp8rcp81a3-xdg-desktop-portal-gtk-1.15.3/libexec/xdg-desktop-portal-gtk
dominikh    5839  0.0  0.0 933104 32168 ?        Ssl  Apr27   0:15 /nix/store/nk28s0hhk9sf31rvz9j8an009rr851q8-xdg-desktop-portal-kde-6.6.4/libexec/xdg-desktop-portal-kde

> /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-desktop-portal --version
xdg-desktop-portal 1.20.4
```

Unfortunately I haven't been able to reproduce it yet. The uptime of the system and the session was around 4 days and my desktop environment is KDE. 

I do have a 5 GB coredump of the process, created with gcore, but currently no tools to analyze it in any useful manner. It compresses to a mere 145 MB and I'd be willing to share it privately if that'd be of any help.

Edit:

journalctl for the process from boot until I killed it:

```
Apr 27 21:21:32 chulak systemd[3881]: Starting Portal service...
Apr 27 21:21:32 chulak /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-desktop-portal[5151]: Choosing gtk.portal for org.freedesktop.impl.portal.Lockdown as a last-resort fallback
Apr 27 21:21:37 chulak systemd[3881]: Started Portal service.
Apr 27 23:10:31 chulak /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-desktop-portal[5151]: Realtime error: Could not get pidns for pid 156307: Could not fstatat ns/pid: Not a directory
Apr 27 23:10:32 chulak /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-desktop-portal[5151]: Realtime error: Could not get pidns for pid 156307: Could not fstatat ns/pid: Not a directory
Apr 30 17:18:34 chulak /nix/store/hn4yqa95qmna06rdhgyxr9pjzqhk231v-xdg-desktop-portal-1.20.4/libexec/xdg-desktop-portal[5151]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
May 02 03:35:36 chulak systemd[3881]: xdg-desktop-portal.service: Consumed 58.062s CPU time over 2d 5h 49min 15.653s wall clock time, 4.3G memory peak.
```

That is a lot of memory given the small amount of CPU time.

**Comment by dominikh** [comment]
The following seems to reproduce the problem:

```
for i in $(seq 1 2000); do
  busctl --user call \
    org.freedesktop.portal.Desktop \
    /org/freedesktop/portal/desktop \
    org.freedesktop.portal.Settings \
    Read ss org.freedesktop.appearance color-scheme \
    >/dev/null 2>&1 || true
done

for i in $(seq 1 200000); do
  busctl --user call \
    org.freedesktop.DBus \
    /org/freedesktop/DBus \
    org.freedesktop.DBus \
    GetId \
    >/dev/null 2>&1 || true
done
```

This causes memory usage of the process to increase drastically, and it doesn't seem to ever go down again. The first loop has fairly small impact on memory usage, but is required for the second loop to reproduce the issue.

But I see now that #1815 isn't part of the 1.20.4 release. Presumably that PR fixed this very issue?

**Comment by swick** [comment]
I did run the reproducer on main and it didn't increase the memory usage, so I assume this is indeed fixed.
