### ISSUE TITLE
If a user is shown a /run/user/<uid>/doc/<hex_id_number> path, it should be considered a bug

### ISSUE THREAD

**Issue by hzulla** [flatpak/xdg-desktop-portal#973]
Hi there,

#886 was closed as "not planned".

However, I'd argue that every time the user is shown a folder path starting with `/run/user/<uid>/doc/<hex_id_number>`, it should be considered a bug and a proper warning or error message should be returned to the application, so that application developers fix this on their side of the code.

Thanks.

**Comment by ssokolow** [comment]
I think it's fundamentally an xdg-desktop-portal bug, because:

1. If the xdg-desktop-portal invisibly mapped from a non-portal path to a portal path when the user clicked OK, then it makes sense to do the reverse when presenting paths to the user for consideration. Otherwise, it's like typing `google.com` into the browser's address bar and watching as the browser arbitrarily replaces it with `142.251.41.46`.
2. If it's a problem with the applications, why does the portal even honour their request to set a path in the first place? Clearly, there's a mechanism for it, so clearly the obvious answer is that the mechanism is only half-implemented and, thus, is not symmetrical with the mechanism that *produced* those paths.
3. It makes no sense to ask all applications to individually work around something that could be fixed once in a single central location.

That leaves one of two possible conclusions:

1. It's a bug caused by xdg-desktop-portal having left this feature unfinished
2. The ability for applications to specify directories to open the dialog to is deprecated and will be removed.

..and, honestly, I think treating it as number 2 would be a *huge* mistake, given all the situations where there's legitimate value in remembering more than one "last used" location per application. (eg. a project that wants to open a file chooser inside the directory returned by a previous call to a directory chooser, a tabbed or single-proces-multiple-window interface which wants to remember the last-used path per-document, etc.)

To achieve those features, you need some kind of permission/capability token that gets handed to the application and which it can then hand back... which is exactly what a documents portal path is. Imagine if the Linux kernel would accept paths, but things like `ls` would return listings of raw inode numbers.

**Comment by xhorak** [comment]
This should help https://github.com/flatpak/xdg-desktop-portal/pull/1007 for the SaveFile dialog.

**Comment by lissyx** [comment]
> This should help #1007 for the SaveFile dialog.

@xhorak Can you be explicit, is your fix actually fixing the present issue, or is some more work required ?

**Comment by xhorak** [comment]
The fix is translating given /run/user/<uid>/doc/<hex_id_number> path to the host path. So it should generally fix this issue.

**Comment by lissyx** [comment]
> The fix is translating given /run/user//doc/<hex_id_number> path to the host path. So it should generally fix this issue.

I applied manually (I hope I applied it correctly because there were a bunch of changes) to 1.14.4 from ubuntu package, but there's no improvement in behavior on firefox usecase:
```
XDP: Handling SaveFile
XDP: convert uri file:/run/user/1000/gvfs/smb-share:server=192.168.1.36,share=documents/Patches/QPdfPresenterConsole-2.7.0-Darwin-x86_64.zip -> file:///run/user/1000/doc/d289bd10/QPdfPresenterConsole-2.7.0-Darwin-x86_64.zip

XDP: Handling SaveFile
XDP: SaveFile: translating current_folder value '/run/user/1000/doc/d289bd10' to host path '/run/user/1000/gvfs/smb-share:server=192.168.1.36,share=documents/Patches'
```

Next time I have the save dialog, it's using a `/run/xxx` path

**Comment by lissyx** [comment]
```
diff -urw xdg_orig/xdg-desktop-portal-1.14.4/src/documents.c xdg/xdg-desktop-portal-1.14.4/src/documents.c
--- xdg_orig/xdg-desktop-portal-1.14.4/src/documents.c	2022-04-27 20:49:03.000000000 +0200
+++ xdg/xdg-desktop-portal-1.14.4/src/documents.c	2023-05-23 16:28:53.791489190 +0200
@@ -33,6 +33,7 @@
 #include "xdp-dbus.h"
 #include "xdp-utils.h"
 #include "document-enums.h"
+#include "document-portal-dbus.h"
 
 static XdpDocuments *documents = NULL;
 static char *documents_mountpoint = NULL;
@@ -224,3 +225,20 @@
 
   return real_path;
 }
+
+char *
+get_real_path_for_doc_id (const char *doc_id)
+{
+  gboolean ret = FALSE;
+  char *real_path = NULL;
+  g_autoptr (GError) error = NULL;
+
+  ret = xdp_documents_call_info_sync (documents, doc_id, &real_path, NULL, NULL, &error);
+  if (!ret)
+    {
+      g_debug ("document portal error for doc id '%s': %s", doc_id, error->message);
+      return NULL;
+    }
+
+  return real_path;
+}
diff -urw xdg_orig/xdg-desktop-portal-1.14.4/src/documents.h xdg/xdg-desktop-portal-1.14.4/src/documents.h
--- xdg_orig/xdg-desktop-portal-1.14.4/src/documents.h	2022-04-27 20:48:39.000000000 +0200
+++ xdg/xdg-desktop-portal-1.14.4/src/documents.h	2023-05-23 16:25:41.482202994 +0200
@@ -33,3 +33,5 @@
 
 char *get_real_path_for_doc_path (const char *path,
                                   XdpAppInfo *app_info);
+
+char *get_real_path_for_doc_id (const char *doc_id);
diff -urw xdg_orig/xdg-desktop-portal-1.14.4/src/file-chooser.c xdg/xdg-desktop-portal-1.14.4/src/file-chooser.c
--- xdg_orig/xdg-desktop-portal-1.14.4/src/file-chooser.c	2022-04-27 20:49:03.000000000 +0200
+++ xdg/xdg-desktop-portal-1.14.4/src/file-chooser.c	2023-05-23 16:07:37.496826601 +0200
@@ -559,6 +559,53 @@
   g_task_run_in_thread (task, send_response_in_thread_func);
 }
 
+/* Calling Lookup on a nonexisting path does not work, so we
+ * pull the doc id out of the path manually.
+ */
+static gboolean
+looks_like_document_portal_path (const char *path,
+                                 char **guessed_docid)
+{
+  const char *prefix = "/run/user/";
+  char *docid;
+  char *p, *q;
+
+  if (!g_str_has_prefix (path, prefix))
+    return FALSE;
+
+  p = strstr (path, "/doc/");
+  if (!p)
+    return FALSE;
+
+  p += strlen ("/doc/");
+  q = strchr (p, '/');
+  if (q)
+    docid = g_strndup (p, q - p);
+  else
+    docid = g_strdup (p);
+
+  if (docid[0] == '\0')
+    {
+      g_free (docid);
+      return FALSE;
+    }
+
+  *guessed_docid = docid;
+  return TRUE;
+}
+
+static char *
+get_host_folder_for_doc_id (const char *doc_id)
+{
+  gchar *host_folder = NULL;
+  g_autofree char *real_path = get_real_path_for_doc_id (doc_id);
+  if (real_path)
+    {
+      host_folder = g_path_get_dirname (real_path);
+    }
+  return host_folder;
+}
+
 static gboolean
 handle_save_file (XdpFileChooser *object,
                   GDBusMethodInvocation *invocation,
@@ -595,6 +642,31 @@
       return G_DBUS_METHOD_INVOCATION_HANDLED;
     }
 
+  
+  {
+      g_autoptr(GVariant) value =
+        g_variant_lookup_value (arg_options, "current_folder", G_VARIANT_TYPE_BYTESTRING);
+
+      if (value)
+        {
+          const char *path_from_app = g_variant_get_bytestring (value);
+          g_autofree char *host_path = g_strdup (path_from_app);
+          g_autofree char *doc_id_from_app = NULL;
+          if (looks_like_document_portal_path (host_path, &doc_id_from_app))
+            {
+              char *real_path = get_host_folder_for_doc_id (doc_id_from_app);
+              if (real_path)
+                {
+                  g_free (host_path);
+                  host_path = real_path;
+                }
+              g_debug ("SaveFile: translating current_folder value '%s' to host path '%s'", path_from_app, host_path);
+            }
+          g_variant_builder_add (&options, "{sv}", "current_folder",
+                                g_variant_new_bytestring (host_path));
+        }
+  }
+
   impl_request = xdp_impl_request_proxy_new_sync (g_dbus_proxy_get_connection (G_DBUS_PROXY (impl)),
                                                   G_DBUS_PROXY_FLAGS_NONE,
                                                   g_dbus_proxy_get_name (G_DBUS_PROXY (impl)),

**Comment by xhorak** [comment]
Hm, I don't thing the gvfs filesystem is supported. Please try the host home filesystem first.

**Comment by lissyx** [comment]
ok, I know sergio was working on a fix for `gvfs` as well.

**Comment by lissyx** [comment]
@xhorak So I can reproduce with a bit of python:
```
$ cat dbus_test_FileChooser_fixed.py 
from gi.repository import Gio, GLib

mainloop = GLib.MainLoop()

bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
file_chooser = Gio.DBusProxy.new_sync(bus, Gio.DBusProxyFlags.NONE, None,
                                "org.freedesktop.portal.Desktop",
                                "/org/freedesktop/portal/desktop",
                                "org.freedesktop.portal.FileChooser", None)

rv = file_chooser.call_sync("SaveFile",
                 GLib.Variant(
                     "(ssa{sv})", (
                         "", # parent_window
                         "Save File", # title
                         {
                            "current_folder": GLib.Variant("ay", b"/run/user/1000/doc/8a722569/\0"),
                            "current_name": GLib.Variant("s", "toto.html"),
                         }
                     )
                 ),
                 Gio.DBusCallFlags.NO_AUTO_START,
                 GLib.MAXINT,
                 None)

def handler(dbus, sender, request, interface, method, value):
    uri = value[1]["uris"][0]
    f = Gio.File.new_for_uri(uri)
    print("f", f.get_path())
    mainloop.quit()

request_handle = rv.unpack()[0]
bus.signal_subscribe("org.freedesktop.portal.Desktop",
                     "org.freedesktop.portal.Request",
                     "Response",
                     request_handle,
                     None,
                     Gio.DBusSignalFlags.NO_MATCH_RULE,
                     handler)

mainloop.run()
```

The path is hardcoded from what I got locally, and the translation works because I see the following in `/usr/libexec/xdg-desktop-portal -rv`, but the UI still shows the wrong path:
```
XDP: Handling SaveFile
XDP: SaveFile: translating current_folder value '/run/user/1000/doc/8a722569/' to host path '/tmp'
```

![Uploading Screenshot_ubuntu22.04_2023-05-24_10:24:31.png…]()

**Comment by lissyx** [comment]
```
$ dbus-monitor --session "interface=org.freedesktop.portal.FileChooser"
signal time=1684918603.302174 sender=org.freedesktop.DBus -> destination=:1.346 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.346"
signal time=1684918603.302200 sender=org.freedesktop.DBus -> destination=:1.346 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.346"
method call time=1684918605.065437 sender=:1.347 -> destination=:1.337 serial=8 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=SaveFile
   string ""
   string "Save File"
   array [
      dict entry(
         string "current_folder"
         variant             array of bytes "/run/user/1000/doc/8a722569/" + \0
      )
      dict entry(
         string "current_name"
         variant             string "toto.html"
      )
   ]
```

**Comment by lissyx** [comment]
OK, so the call to `xdp_impl_file_chooser_call_save_file` is made with the wrong value:
`XDP: SaveFile: xdp_impl_file_chooser_call_save_file options->current_folder=/run/user/1000/doc/8a722569/`

**Comment by xhorak** [comment]
I don't see the last backslash in my case:
`XDP: SaveFile: translating current_folder value '/run/user/1000/doc/9aa00692' to host path '/home/jhorak/done'`
it also seems to be working right for the `/tmp`
`XDP: SaveFile: translating current_folder value '/run/user/1000/doc/afdff3b6' to host path '/tmp'`

Btw which gtk and xdg-desktop-portal-gtk is used?

**Comment by lissyx** [comment]
packages are from ubuntu 22.04

**Comment by lissyx** [comment]
There's a `g_variant_builder_init (&options, G_VARIANT_TYPE_VARDICT);` which likely initialize `current_folde` with the original value, and it looks like the `g_variant_builder_add (&options, "{sv}", "current_folder", g_variant_new_bytestring (host_path));` does not replace it. I know mostly nothing around glib, so I dont know if it's expected or what.

**Comment by xhorak** [comment]
Using the testcase you've given, it works fine in my case, backlash or no backlash:
![image](https://github.com/flatpak/xdg-desktop-portal/assets/2932697/71c493db-c8fd-4d92-9946-781faf20b4d1)

**Comment by lissyx** [comment]
Well for sure, version 1.14.0 used in ubuntu 22.04 package does not change the value.

**Comment by xhorak** [comment]
Please attach `dbus-monitor --session` output regarding request if possible.

**Comment by lissyx** [comment]
And I also dump `options->current_folder` values at:
 - before and after https://github.com/flatpak/xdg-desktop-portal/blob/dbe8633d08dd9f790216df3e8104d82fb555c16f/src/file-chooser.c#L698-L699
 - before calling https://github.com/flatpak/xdg-desktop-portal/blob/dbe8633d08dd9f790216df3e8104d82fb555c16f/src/file-chooser.c#L720-L728

So there is no doubt `GVariantBuilder options` still holds the old value, not the `host_path` one.

**Comment by xhorak** [comment]
Well I've got two calls:
```
method call time=1684920785.386875 sender=:1.475 -> destination=:1.416 serial=8 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=SaveFile
   string ""
   string "Save File"
   array [
      dict entry(
         string "current_folder"
         variant             array of bytes "/run/user/1000/doc/afdff3b6" + \0
      )
      dict entry(
         string "current_name"
         variant             string "toto.html"
      )
   ]
```
the :1.416 is the xdg-desktop-portal
and later the xdg-desktop-portal sends to xdg-desktop-portal-gtk following:
```
method call time=1684920785.388199 sender=:1.416 -> destination=:1.468 serial=271 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.impl.portal.FileChooser; member=SaveFile
   object path "/org/freedesktop/portal/desktop/request/1_475/t"
   string "org.kde.konsole"
   string ""
   string "Save File"
   array [
      dict entry(
         string "current_name"
         variant             string "toto.html"
      )
      dict entry(
         string "current_folder"
         variant             array of bytes "/tmp" + \0
      )
   ]
```

**Comment by lissyx** [comment]
I tripled and I only get one dbus:
```
method call time=1684921319.350216 sender=:1.372 -> destination=:1.368 serial=8 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=SaveFile
   string ""
   string "Save File"
   array [
      dict entry(
         string "current_folder"
         variant             array of bytes "/run/user/1000/doc/8a722569" + \0
      )
      dict entry(
         string "current_name"
         variant             string "toto.html"
      )
   ]
```

And for sure what is sent from `xdg-deskop-portal` over dbus is wrong (`/run/user/1000/doc/8a722569`), as I said out of `options`.

**Comment by xhorak** [comment]
So the :1.368 is which service? Please lookup in the d-feet.

**Comment by xhorak** [comment]
What's interesting is that the `org.freedesktop.impl.portal.FileChooser` is not called from the xdg-desktop-portal.

**Comment by lissyx** [comment]
`:1.383` is my python code, `:1.368` is `xdg-desktop-portal -rv`

**Comment by lissyx** [comment]
> What's interesting is that the `org.freedesktop.impl.portal.FileChooser` is not called from the xdg-desktop-portal.

Sorry but I cannot understand why you insist checking dbus when it is clear that the `options` `GVariant` that is being used to send the open request is using the wrong value ...

**Comment by xhorak** [comment]
The `xdp_filter_options` is here to filter the `current_folder` from the new options .I think you miss the this changeset:
https://github.com/flatpak/xdg-desktop-portal/commit/d3a92486cb7ab4ebddb7d0d42111a1f38e4bc51e#diff-8a0796355b12976b653e60e44e5ba7b9d9b38b4972c677ff930922606329de76L535

**Comment by lissyx** [comment]
> The `xdp_filter_options` is here to filter the `current_folder` from the new options .I think you miss the this changeset: [d3a9248#diff-8a0796355b12976b653e60e44e5ba7b9d9b38b4972c677ff930922606329de76L535](https://github.com/flatpak/xdg-desktop-portal/commit/d3a92486cb7ab4ebddb7d0d42111a1f38e4bc51e#diff-8a0796355b12976b653e60e44e5ba7b9d9b38b4972c677ff930922606329de76L535)

My local rebuild does include this since the beginning: https://github.com/flatpak/xdg-desktop-portal/issues/973#issuecomment-1559575623

**Comment by lissyx** [comment]
Wait, why did it come back, I did remove it when I applied the changes yesterday.

**Comment by lissyx** [comment]
And boom, now it works. Thanks @xhorak for hinting on that, because I did remove it, that is for sure. Something must have tricked me and applied it back.

**Comment by xhorak** [comment]
Good to hear that.

**Comment by GeorgesStavracas** [comment]
Seems like this was fixed by https://github.com/flatpak/xdg-desktop-portal/pull/1007 and is now part of the 1.18.0 release. I'll close this issue. Please reopen if I misunderstood the current state.

**Comment by hyuri** [comment]
Still an issue in 1.18.

Selecting `/home/user/Videos/Calls` in Zoom returns this:
![image](https://github.com/flatpak/xdg-desktop-portal/assets/18584014/c18d0edb-5d26-4703-a707-346ea8bc0070)

This `/run/user/1000/doc/...` is meaningless to the user. The user only knows, cares about and interacts with `/home/user/Videos/Calls` so that's what should always be shown.

And it's not the responsibility of applications to convert these weird paths, since the file will be saved in `/home/user/Videos/Calls` anyways, the app should care about storing and displaying that path. The portal should handle converting these paths back and forth.

**Comment by Abdull** [comment]
yet another phenomenon with flatpak-Zoom and the directory issue under discussion: downloading a file attached to a chat group message opens the Save dialog, but the filename field is empty, instead of being prefilled with the filename.
